import { AUTHING_APP_ID } from '../config/authing';
interface LotterySubmission { id:string; userName:string; content:string; shippingAddress:string; status:'pending'|'approved'|'rejected'; reviewNote:string|null; reviewerName:string|null; createdAt:string; attachments:Array<{id:string;name:string;mime:string;size:number}>; }
interface StoredLoginState { accessToken:string; expireAt:number; }
const key=`qdrive-auth:${AUTHING_APP_ID}:session`;
const readState=():StoredLoginState|null=>{try{const s=JSON.parse(localStorage.getItem(key)||'') as Partial<StoredLoginState>;return typeof s.accessToken==='string'&&typeof s.expireAt==='number'&&s.expireAt>Date.now()?s as StoredLoginState:null;}catch{return null;}};
const readJson=async<T>(r:Response):Promise<T>=>{const v=await r.json() as T&{error?:string};if(!r.ok)throw new Error(v.error||'请求未完成。');return v;};
function init(root:HTMLElement){
 const status=root.querySelector<HTMLElement>('[data-lottery-admin-status]'),list=root.querySelector<HTMLElement>('[data-lottery-admin-list]'),pagination=root.querySelector<HTMLElement>('[data-lottery-admin-pagination]'),filters=root.querySelector<HTMLFormElement>('[data-lottery-admin-filters]'),user=root.querySelector<HTMLInputElement>('[data-filter-user]'),keyword=root.querySelector<HTMLInputElement>('[data-filter-keyword]'),stateFilter=root.querySelector<HTMLSelectElement>('[data-filter-status]'); if(!status||!list||!pagination||!filters||!user||!keyword||!stateFilter)return;
 const settingsForm=root.querySelector<HTMLFormElement>('[data-lottery-settings-form]'),enabled=root.querySelector<HTMLInputElement>('[data-lottery-enabled]'),mode=root.querySelector<HTMLSelectElement>('[data-lottery-mode]'),first=root.querySelector<HTMLInputElement>('[data-lottery-first]'),second=root.querySelector<HTMLInputElement>('[data-lottery-second]'),third=root.querySelector<HTMLInputElement>('[data-lottery-third]'),draw=root.querySelector<HTMLButtonElement>('[data-lottery-draw]');
 let all:LotterySubmission[]=[],filtered:LotterySubmission[]=[],page=1; const size=5;
 const setStatus=(m='',e=false)=>{status.textContent=m;status.classList.toggle('is-error',e);};
 const load=async()=>{const s=readState();if(!s)throw new Error('请先登录管理员账户。');const r=await fetch('/api/admin/lotteries',{headers:{Authorization:`Bearer ${s.accessToken}`}});const v=await readJson<{submissions:LotterySubmission[];settings?:{enabled:boolean;mode:string;firstProbability:number;secondProbability:number;thirdProbability:number;firstCount:number;secondCount:number;thirdCount:number}}>(r);all=v.submissions;if(v.settings&&enabled&&mode&&first&&second&&third){enabled.checked=v.settings.enabled;mode.value=v.settings.mode;first.value=String(v.settings.mode==='count'?v.settings.firstCount:v.settings.firstProbability);second.value=String(v.settings.mode==='count'?v.settings.secondCount:v.settings.secondProbability);third.value=String(v.settings.mode==='count'?v.settings.thirdCount:v.settings.thirdProbability);}apply();};
 const render=()=>{list.replaceChildren(); const labels={pending:'待审核',approved:'已通过',rejected:'已驳回'} as const; filtered.slice((page-1)*size,page*size).forEach(x=>{const card=document.createElement('article');card.className='contribution-admin__card'; const meta=document.createElement('div');meta.className='contribution-admin__meta'; const ident=document.createElement('div');const name=document.createElement('strong');name.textContent=x.userName;const time=document.createElement('time');time.textContent=` · ${new Date(x.createdAt).toLocaleString('zh-CN')}`;ident.append(name,time);const badge=document.createElement('span');badge.className='contribution-admin__badge';badge.textContent=labels[x.status];meta.append(ident,badge);card.append(meta);const content=document.createElement('p');content.className='contribution-admin__content';content.textContent=`活动凭证：${x.content||'未填写'}`;card.append(content);const address=document.createElement('p');address.textContent=`收货信息：${x.shippingAddress}`;card.append(address);if(x.attachments.length){const files=document.createElement('p');files.textContent=`附件：${x.attachments.map(a=>a.name).join('、')}`;card.append(files);}if(x.status==='pending'){const form=document.createElement('div');form.className='contribution-admin__review';const note=document.createElement('textarea');note.maxLength=500;note.placeholder='审核备注（可选）';const actions=document.createElement('div');actions.className='contribution-admin__actions';(['rejected','approved'] as const).forEach(st=>{const b=document.createElement('button');b.type='button';b.textContent=st==='approved'?'通过申请':'驳回';b.addEventListener('click',async()=>{b.disabled=true;try{const s=readState();if(!s)throw new Error('登录状态已过期。');await readJson(await fetch('/api/admin/lotteries',{method:'PATCH',headers:{Authorization:`Bearer ${s.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({id:x.id,status:st,note:note.value.trim()})}));setStatus(st==='approved'?'抽奖申请已通过。':'抽奖申请已驳回。');await load();}catch(e){setStatus(e instanceof Error?e.message:'处理失败。',true);}finally{b.disabled=false;}});actions.append(b);});form.append(note,actions);card.append(form);}else{const reviewed=document.createElement('p');reviewed.className='contribution-admin__reviewed';reviewed.textContent=`审核人：${x.reviewerName||'历史记录未保存审核人'}${x.reviewNote?` · ${x.reviewNote}`:''}`;card.append(reviewed);}list.append(card);});
  pagination.replaceChildren();const count=Math.max(1,Math.ceil(filtered.length/size));if(filtered.length){const prev=document.createElement('button');prev.type='button';prev.textContent='上一页';prev.disabled=page<=1;prev.onclick=()=>{page--;render();};const label=document.createElement('span');label.textContent=`第 ${page} 页，共 ${count} 页`;const next=document.createElement('button');next.type='button';next.textContent='下一页';next.disabled=page>=count;next.onclick=()=>{page++;render();};pagination.append(prev,label,next);}
 };
 const apply=()=>{const u=user.value.trim().toLocaleLowerCase(),k=keyword.value.trim().toLocaleLowerCase(),s=stateFilter.value;filtered=all.filter(x=>(!u||x.userName.toLocaleLowerCase().includes(u))&&(!k||`${x.content} ${x.shippingAddress} ${x.attachments.map(a=>a.name).join(' ')}`.toLocaleLowerCase().includes(k))&&(!s||x.status===s));page=1;render();setStatus(filtered.length===all.length?'':`筛选出 ${filtered.length} 条，共 ${all.length} 条。`);};
 [user,keyword,stateFilter].forEach(x=>{x.addEventListener('input',apply);x.addEventListener('change',apply);});filters.addEventListener('reset',()=>setTimeout(apply,0));
 if(settingsForm&&enabled&&mode&&first&&second&&third){settingsForm.addEventListener('submit',async e=>{e.preventDefault();const s=readState();if(!s)return setStatus('登录状态已过期。',true);const value=Number(first.value)||0,value2=Number(second.value)||0,value3=Number(third.value)||0;try{await readJson(await fetch('/api/admin/lotteries',{method:'POST',headers:{Authorization:`Bearer ${s.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({action:'settings',settings:{enabled:enabled.checked,mode:mode.value,firstProbability:mode.value==='probability'?value:0,secondProbability:mode.value==='probability'?value2:0,thirdProbability:mode.value==='probability'?value3:0,firstCount:mode.value==='count'?value:0,secondCount:mode.value==='count'?value2:0,thirdCount:mode.value==='count'?value3:0}})}));setStatus('抽奖设置已保存。');}catch(e2){setStatus(e2 instanceof Error?e2.message:'保存失败。',true);}});}
 if(draw){draw.addEventListener('click',async()=>{const s=readState();if(!s)return setStatus('登录状态已过期。',true);if(!confirm('确定按当前设置立即开奖吗？开奖后本轮参与记录将不能再次抽取。'))return;draw.disabled=true;try{const result=await readJson<{result:{winners:number}}>(await fetch('/api/admin/lotteries',{method:'POST',headers:{Authorization:`Bearer ${s.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({action:'draw'})}));setStatus(`开奖完成，共产生 ${result.result.winners} 位中奖用户。`);await load();}catch(e){setStatus(e instanceof Error?e.message:'开奖失败。',true);}finally{draw.disabled=false;}});}
 void load().catch(e=>setStatus(e instanceof Error?e.message:'无法读取抽奖申请。',true));
}
document.querySelectorAll<HTMLElement>('[data-lottery-admin-root]').forEach(init);
